# Generated by Django 5.2.6 on 2025-09-22 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproject',
            options={'verbose_name': 'Category Project', 'verbose_name_plural': 'Category Projects'},
        ),
        migrations.AlterModelOptions(
            name='imageproject',
            options={'verbose_name': 'Image Project', 'verbose_name_plural': 'Image Projects'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_auther', to=settings.AUTH_USER_MODEL, verbose_name='Project Auther'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='categoryproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='projects.categoryproject', verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cover_description',
            field=models.TextField(max_length=100000, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=100000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Project Title'),
        ),
    ]
