# Generated by Django 5.2.6 on 2025-09-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_categoryproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
