# Generated by Django 5.2.6 on 2025-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
