# Generated by Django 5.2.6 on 2025-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_duration_projects_status_projects_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
