# Generated by Django 5.2.6 on 2025-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='categoryskills',
            options={'verbose_name': 'Category Skill', 'verbose_name_plural': 'Category Skills'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='exp',
            options={'verbose_name': 'EXP', 'verbose_name_plural': 'EXPs'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='myskills',
            options={'verbose_name': 'My Skill', 'verbose_name_plural': 'My Skills'},
        ),
        migrations.AlterModelOptions(
            name='professionalexperience',
            options={'verbose_name': 'Professional Experience', 'verbose_name_plural': 'Professional Experiences'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
