# Generated by Django 5.2.6 on 2025-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options_alter_categoryskills_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='exp',
        ),
        migrations.AddField(
            model_name='exp',
            name='exp',
            field=models.ManyToManyField(related_name='exp', to='about.professionalexperience'),
        ),
    ]
