# Generated by Django 5.2.6 on 2025-09-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_exp_exp_exp_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryskills',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myskills',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
