# Generated by Django 5.2.6 on 2025-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_categoryskills_icon_myskills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='available_for_hire',
            field=models.BooleanField(default=True),
        ),
    ]
