# Generated by Django 5.2.6 on 2025-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_available_for_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='total_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
